services:
  web:
    build: .
    ports:
      - 5000:80
    depends_on:
      - server

  db:
    image: surrealdb/surrealdb:latest
    command:
      - start
      - --log=warn
      - --user=root
      - --pass=root
      - rocksdb:/mydata/data.db
    restart: always
    volumes:
      - db-data:/mydata

  server:
    build: ./server
    environment:
      - DB_URL=http://db:8000/rpc
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - PORT=3000
      - JWT_SECRET=verysecure
    volumes:
      - files:/files
    depends_on:
      - db

volumes:
  db-data:
  files: