version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ../..:/workspaces:cached
    depends_on:
      - db
    command: sleep infinity

  db:
    image: surrealdb/surrealdb:latest
    volumes:
      - db-data:/mydata:rw
    entrypoint:
      - /surreal
      - start
      - --strict
      - --user
      - root
      - --pass
      - root
      - memory

volumes:
  db-data:
