version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ../..:/workspaces:cached
    depends_on:
      - db
    command: sleep infinity

  db:
    image: surrealdb/surrealdb:latest
    volumes:
      - ../data.dev/surrealdb:/surrealdb:rw
    entrypoint:
      - /surreal
      - start
      - --strict
      - --user
      - root
      - --pass
      - root
      - surrealkv://surrealdb

  nginx:
    image: nginx:alpine
    volumes:
      - ../data.dev/nginx:/app/static:ro
      - ../web/dist:/app/www:ro
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
